### ISSUE TITLE
Documentation, unit-test and workflows

### ISSUE THREAD

**Issue by EtienneCmb** [brainets/hoi#14]
HI @Dishie2498, @Mattehub, @brovelli. Please find below the following steps we will go through until the end of the GSoC.

# 1. Documentation

## 1.1 Gallery of examples

- [x] @Dishie2498 is currently working on getting up the gallery of examples (#15)
- [ ] @Mattehub and I we will then fill the gallery with examples illustrating 1) the HOI metrics and 2) benchmark showcasing JAX (performance claims)

## 1.2 Theoretical background and README

- [ ] @Mattehub is going to write the *Theoretical background* required to understand HOI. This includes 1) explaining entropy and mutual information (gcmi, knn, kernel and binning) and mutual-information and 2) explain the metric of HOI.
- [ ] @Mattehub will also propose a high-level description of the repo that is going to be used in the README. This should include: 1) the overall goal of the HOI, 2) explain how to install it and the required dependencies such as sponsors (GSoC)

## 1.3 Logo

- [ ] @Dishie2498 will make a proposition for the logo. Propositions are open to others @Mattehub or @brovelli (or @StanSStanman <3) 

## 1.4 License

- [x] Add license (BSD claused 3)

# 2. Data simulation

- [x] @Mattehub made a function to simulate HOI. I'll review the code to integrate it inside `hoi.simulation`. Those simulations are then going to be used for the gallery of examples
- [x] @Dishie2498 will then integrate inside the documentation

# 3. Testing functionalities and workflows

## 3.1 Unit-testing

- [x] @Dishie2498 and I we will write the unit-tests (functional and smoke tests)

## 3.2 Workflows

Here are the workflows that are going to be required (@Dishie2498 and I) :

- [x] Github action to test code quality ([example](https://github.com/brainets/frites/blob/master/.github/workflows/flake.yml))
- [ ] Github action to send the repo to PyPi ([example](https://github.com/brainets/frites/blob/master/.github/workflows/pypi-publish.yml))
- [x] Github action to test the functionalities on several python version ([example](https://github.com/brainets/frites/blob/master/.github/workflows/test_doc.yml)). This action implements first unit-testing and then publish the doc.
- [ ] It would be great if could add dropdown menu in the doc to select the documentation associated with each release (see [mne-python](https://mne.tools/stable/index.html)
- [x] Add badges to the readme.rst and index.rst

**Comment by brovelli** [comment]
The link below is missing (in the main page https://github.com/brainets/hoi)
https://brainets.github.io/hoi/overview/ovw_theory.html
