### ISSUE TITLE
GSoC - Implementation of the boostrap

### ISSUE THREAD

**Issue by EtienneCmb** [brainets/hoi#3]
Python implementation of the boostraps for selecting significant multiplets + confidence interval estimation. For reference, here's the [matlab version](https://github.com/danielemarinazzo/HOI/blob/main/hoi_exhaustive_loop_zerolag_all.m#L132). 

- [ ] For the resampling, we should directly use [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.utils.resample.html). You can also look at a [past implementation](https://github.com/brainets/hoi_bhk/blob/main/etienne/hoi_bhk/oinfo.py#L50). The function defining the indices for resampling should be added to `hoi/core/combinatory.py`
- [ ] Compute significance, CI and comparison between orders

**Comment by Mattehub** [comment]
About this, I have already the functions for computing, in the case of 2-dimensional data the confidence interval of each multiplet. In case it is useful I can clean them and push them.  Let me know.

**Comment by EtienneCmb** [comment]
I planned to make an example instead. I'll make an example showcasing CI and significance testing using Frites.

**Comment by Mattehub** [comment]
Ok, super!
