### ISSUE TITLE
[REVIEW]: Missing DOIs

### ISSUE THREAD

**Issue by pitmonticone** [brainets/hoi#60]
Dear authors,

Please review the [missing DOIs](https://github.com/openjournals/joss-reviews/issues/7360#issuecomment-2415799470) and ensure the references are updated accordingly.

Once you have completed this, please confirm by posting the following comment in the review thread [here](https://github.com/openjournals/joss-reviews/issues/7360):

```
@editorialbot check references
```

REVIEW ISSUE: https://github.com/openjournals/joss-reviews/issues/7360

**Comment by EtienneCmb** [comment]
Hi @pitmonticone,

Missing DOI were added witht eh commit [cfafda5](https://github.com/brainets/hoi/commit/cfafda54d3127a7850e74d39bdd519df31cc7f89). Please see the report of the editorial bot [here](https://github.com/openjournals/joss-reviews/issues/7360#issuecomment-2443861769)

**Comment by pitmonticone** [comment]
I consider this issue resolved.
