### ISSUE TITLE
[REVIEW]: No plots in `plot_tutorial_core.py`

### ISSUE THREAD

**Issue by pitmonticone** [brainets/hoi#64]
Dear authors,

The name of the example script `examples/it/plot_tutorial_core.py` does not perform any plotting. It may be helpful to either rename the script to better reflect its functionality or modify the script to include plotting if that was the intended purpose.

REVIEW ISSUE: https://github.com/openjournals/joss-reviews/issues/7360

**Comment by EtienneCmb** [comment]
Indeed. We used the terminology `plot_` because sphinx-gallery uses this pattern to build the documentation. We changed it for `examples/it/tuto_core.py` in commit 29454b8

**Comment by pitmonticone** [comment]
I consider this issue resolved.
