### ISSUE TITLE
[REVIEW]: No plots in `plot_jax.py`

### ISSUE THREAD

**Issue by pitmonticone** [brainets/hoi#68]
Dear authors,

The name of the example script `examples/miscellaneous/plot_jax.py` does not perform any plotting. It may be helpful to either rename the script to better reflect its functionality or modify the script to include plotting if that was the intended purpose.

REVIEW ISSUE: https://github.com/openjournals/joss-reviews/issues/7360

**Comment by EtienneCmb** [comment]
Indeed, we used `plot_jax` for the same reason as #64. We renamed the file for `examples/miscellaneous/plot_jax.py`.

Thanks !
